1.Create a Notebook to demonstrate NumPy Operations.
     
2.Create an array that starts from the integer 1, ends at 20, incremented by 3.
     
3.Create a new array of shape 3 with random numbers between 0 and 1.
     
4.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 
     
Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.
       
5.Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.
     
6.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 
     
Demonstrate the case when it is not possible to.
      
7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
     
Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).
      
8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.
     
9. Add Markdown text, with a headline, that provides a very brief overview of the graphs (e.g., one sentence for each). 
     
  Feel free to add additional Markdown elements (description/additional comments)
        
10. Push the notebook to your lab-submission fork, and create a PR

In [4]:
import numpy as np

# Step 2: Create an array that starts from 1, ends at 20, incremented by 3
array_step2 = np.arange(1, 21, 3)
print("Step 2 - Array with step 3:\n", array_step2)

# Step 3: Create a new array of shape (3,) with random numbers between 0 and 1
array_step3 = np.random.rand(3)
print("\nStep 3 - Random array of shape 3:\n", array_step3)

# Step 4: Create a 2D array and slice it
array_2d = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

# First two rows
first_two_rows = array_2d[:2, :]

# Last two rows
last_two_rows = array_2d[1:, :]

print("\nStep 4 - Original 2D Array:\n", array_2d)
print("First two rows:\n", first_two_rows)
print("Last two rows:\n", last_two_rows)


# Step 5: Create two 2x2 arrays and demonstrate stacking and splitting
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Vertical stack
vertical_stack = np.vstack((a, b))

# Horizontal stack
horizontal_stack = np.hstack((a, b))

# Split arrays vertically and horizontally
split_vertical = np.vsplit(vertical_stack, 2)
split_horizontal = np.hsplit(horizontal_stack, 2)

print("\nStep 5 - Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)
print("Vertical Split:\n", split_vertical)
print("Horizontal Split:\n", split_horizontal)


# Step 6: Matrix multiplication check
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

# Check if multiplication is possible
if X.shape[1] == Y.shape[0]:
    result = np.dot(X, Y)
    print("\nStep 6 - Matrix Multiplication Result:\n", result)
else:
    print("\nStep 6 - Cannot multiply X and Y due to shape mismatch")


# Step 7: Shape, dimensions, and reshape
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("\nStep 7 - Original x shape:", x.shape)
print("Original x dimensions:", x.ndim)

# Reshape x and y to (3,1)
x_reshaped = x.reshape((3, 1))
y_reshaped = y.reshape((3, 1))

print("Reshaped x:\n", x_reshaped)
print("Reshaped y:\n", y_reshaped)
print("x dimensions after reshaping:", x_reshaped.ndim)
print("y dimensions after reshaping:", y_reshaped.ndim)


# Step 8: Broadcasting example with subtraction and multiplication
matrix_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector_1x3 = np.array([1, 0, 1])

# Broadcasting subtraction and multiplication
broadcast_sub = matrix_3x3 - vector_1x3
broadcast_mul = matrix_3x3 * vector_1x3

print("\nStep 8 - Original Matrix:\n", matrix_3x3)
print("Vector:\n", vector_1x3)
print("Broadcast Subtraction:\n", broadcast_sub)
print("Broadcast Multiplication:\n", broadcast_mul)


Step 2 - Array with step 3:
 [ 1  4  7 10 13 16 19]

Step 3 - Random array of shape 3:
 [0.13344251 0.286259   0.34684348]

Step 4 - Original 2D Array:
 [[10 20 45]
 [30 12 16]
 [42 17 56]]
First two rows:
 [[10 20 45]
 [30 12 16]]
Last two rows:
 [[30 12 16]
 [42 17 56]]

Step 5 - Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Vertical Split:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
Horizontal Split:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]

Step 6 - Matrix Multiplication Result:
 [[70 28]
 [70 30]
 [60 26]]

Step 7 - Original x shape: (3,)
Original x dimensions: 1
Reshaped x:
 [[ 2]
 [-1]
 [-8]]
Reshaped y:
 [[ 3]
 [ 1]
 [-2]]
x dimensions after reshaping: 2
y dimensions after reshaping: 2

Step 8 - Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector:
 [1 0 1]
Broadcast Subtraction:
 [[0 2 2]
 [3 5 5]
 [6 8 8]]
Broadcast Multiplication:
 [[1 0 3]
 [4 0 6]
 [7 0 9]]


PART-B
 1.Solve the following two system of linear equations using matrices (find the values of x1 and x2) and 
      determine the number of solutions using the functions. 
         1.2x1+3x2-4x3=6,x1-4x2=8
	
         2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8

    2.Publish the notebook as an HTML using GitHub Pages
  In the PR description (created above) - add the direct link to the HTML

In [5]:
import numpy as np

# Step 2: Solve System 1
# Equations:
# 2x1 + 3x2 - 4x3 = 6
# x1 - 4x2 + 0x3 = 8

A1 = np.array([[2, 3, -4],
               [1, -4, 0]])
b1 = np.array([6, 8])

# Use least squares to solve
x1_solution, residuals1, rank1, s1 = np.linalg.lstsq(A1, b1, rcond=None)
print("System 1 Solution (x1, x2, x3):", x1_solution)

System 1 Solution (x1, x2, x3): [ 1.6692112 -1.5826972 -1.8524173]
